// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: data_management.proto

package fin_quotes_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TickerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Price float32                `protobuf:"fixed32,2,opt,name=Price,proto3" json:"Price,omitempty"`
	Time  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=Time,proto3" json:"Time,omitempty"`
}

func (x *TickerRequest) Reset() {
	*x = TickerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_management_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TickerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickerRequest) ProtoMessage() {}

func (x *TickerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_management_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickerRequest.ProtoReflect.Descriptor instead.
func (*TickerRequest) Descriptor() ([]byte, []int) {
	return file_data_management_proto_rawDescGZIP(), []int{0}
}

func (x *TickerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TickerRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TickerRequest) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type TickerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Price float32                `protobuf:"fixed32,2,opt,name=Price,proto3" json:"Price,omitempty"`
	Time  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=Time,proto3" json:"Time,omitempty"`
}

func (x *TickerResponse) Reset() {
	*x = TickerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_management_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TickerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickerResponse) ProtoMessage() {}

func (x *TickerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_management_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickerResponse.ProtoReflect.Descriptor instead.
func (*TickerResponse) Descriptor() ([]byte, []int) {
	return file_data_management_proto_rawDescGZIP(), []int{1}
}

func (x *TickerResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TickerResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TickerResponse) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type MultipleTickerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tickers []*TickerRequest `protobuf:"bytes,1,rep,name=tickers,proto3" json:"tickers,omitempty"` // Массив запросов
}

func (x *MultipleTickerRequest) Reset() {
	*x = MultipleTickerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_management_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultipleTickerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleTickerRequest) ProtoMessage() {}

func (x *MultipleTickerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_management_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleTickerRequest.ProtoReflect.Descriptor instead.
func (*MultipleTickerRequest) Descriptor() ([]byte, []int) {
	return file_data_management_proto_rawDescGZIP(), []int{2}
}

func (x *MultipleTickerRequest) GetTickers() []*TickerRequest {
	if x != nil {
		return x.Tickers
	}
	return nil
}

type MultipleTickerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Responses []*TickerResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"` // Массив ответов
}

func (x *MultipleTickerResponse) Reset() {
	*x = MultipleTickerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_management_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultipleTickerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleTickerResponse) ProtoMessage() {}

func (x *MultipleTickerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_management_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleTickerResponse.ProtoReflect.Descriptor instead.
func (*MultipleTickerResponse) Descriptor() ([]byte, []int) {
	return file_data_management_proto_rawDescGZIP(), []int{3}
}

func (x *MultipleTickerResponse) GetResponses() []*TickerResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

var File_data_management_proto protoreflect.FileDescriptor

var file_data_management_proto_rawDesc = []byte{
	0x0a, 0x15, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x69, 0x0a, 0x0d, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x54,
	0x69, 0x6d, 0x65, 0x22, 0x6a, 0x0a, 0x0e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x2e, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0x41, 0x0a, 0x15, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x07, 0x74, 0x69, 0x63, 0x6b,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x74, 0x69, 0x63, 0x6b, 0x65,
	0x72, 0x73, 0x22, 0x47, 0x0a, 0x16, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x09,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x32, 0x8b, 0x01, 0x0a, 0x15,
	0x44, 0x61, 0x74, 0x61, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2c, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74,
	0x65, 0x73, 0x12, 0x0e, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70,
	0x6c, 0x65, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69,
	0x70, 0x6c, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x17, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6b, 0x6f, 0x6c, 0x6f, 0x62, 0x61, 0x68,
	0x61, 0x2f, 0x66, 0x69, 0x6e, 0x5f, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x2e, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_data_management_proto_rawDescOnce sync.Once
	file_data_management_proto_rawDescData = file_data_management_proto_rawDesc
)

func file_data_management_proto_rawDescGZIP() []byte {
	file_data_management_proto_rawDescOnce.Do(func() {
		file_data_management_proto_rawDescData = protoimpl.X.CompressGZIP(file_data_management_proto_rawDescData)
	})
	return file_data_management_proto_rawDescData
}

var file_data_management_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_data_management_proto_goTypes = []any{
	(*TickerRequest)(nil),          // 0: TickerRequest
	(*TickerResponse)(nil),         // 1: TickerResponse
	(*MultipleTickerRequest)(nil),  // 2: MultipleTickerRequest
	(*MultipleTickerResponse)(nil), // 3: MultipleTickerResponse
	(*timestamppb.Timestamp)(nil),  // 4: google.protobuf.Timestamp
}
var file_data_management_proto_depIdxs = []int32{
	4, // 0: TickerRequest.Time:type_name -> google.protobuf.Timestamp
	4, // 1: TickerResponse.Time:type_name -> google.protobuf.Timestamp
	0, // 2: MultipleTickerRequest.tickers:type_name -> TickerRequest
	1, // 3: MultipleTickerResponse.responses:type_name -> TickerResponse
	0, // 4: DataManagementService.GetQuotes:input_type -> TickerRequest
	2, // 5: DataManagementService.GetMultipleQuotes:input_type -> MultipleTickerRequest
	1, // 6: DataManagementService.GetQuotes:output_type -> TickerResponse
	3, // 7: DataManagementService.GetMultipleQuotes:output_type -> MultipleTickerResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_data_management_proto_init() }
func file_data_management_proto_init() {
	if File_data_management_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_data_management_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TickerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_management_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TickerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_management_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*MultipleTickerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_management_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*MultipleTickerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_data_management_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_management_proto_goTypes,
		DependencyIndexes: file_data_management_proto_depIdxs,
		MessageInfos:      file_data_management_proto_msgTypes,
	}.Build()
	File_data_management_proto = out.File
	file_data_management_proto_rawDesc = nil
	file_data_management_proto_goTypes = nil
	file_data_management_proto_depIdxs = nil
}
