// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: data_management.proto

package fin_quotes_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataManagementService_GetMultipleQuotes_FullMethodName = "/DataManagementService/GetMultipleQuotes"
)

// DataManagementServiceClient is the client API for DataManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataManagementServiceClient interface {
	GetMultipleQuotes(ctx context.Context, in *MultipleTickerRequest, opts ...grpc.CallOption) (*TickerResponse, error)
}

type dataManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataManagementServiceClient(cc grpc.ClientConnInterface) DataManagementServiceClient {
	return &dataManagementServiceClient{cc}
}

func (c *dataManagementServiceClient) GetMultipleQuotes(ctx context.Context, in *MultipleTickerRequest, opts ...grpc.CallOption) (*TickerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TickerResponse)
	err := c.cc.Invoke(ctx, DataManagementService_GetMultipleQuotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataManagementServiceServer is the server API for DataManagementService service.
// All implementations must embed UnimplementedDataManagementServiceServer
// for forward compatibility.
type DataManagementServiceServer interface {
	GetMultipleQuotes(context.Context, *MultipleTickerRequest) (*TickerResponse, error)
	mustEmbedUnimplementedDataManagementServiceServer()
}

// UnimplementedDataManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataManagementServiceServer struct{}

func (UnimplementedDataManagementServiceServer) GetMultipleQuotes(context.Context, *MultipleTickerRequest) (*TickerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMultipleQuotes not implemented")
}
func (UnimplementedDataManagementServiceServer) mustEmbedUnimplementedDataManagementServiceServer() {}
func (UnimplementedDataManagementServiceServer) testEmbeddedByValue()                               {}

// UnsafeDataManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataManagementServiceServer will
// result in compilation errors.
type UnsafeDataManagementServiceServer interface {
	mustEmbedUnimplementedDataManagementServiceServer()
}

func RegisterDataManagementServiceServer(s grpc.ServiceRegistrar, srv DataManagementServiceServer) {
	// If the following call pancis, it indicates UnimplementedDataManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataManagementService_ServiceDesc, srv)
}

func _DataManagementService_GetMultipleQuotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultipleTickerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataManagementServiceServer).GetMultipleQuotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataManagementService_GetMultipleQuotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataManagementServiceServer).GetMultipleQuotes(ctx, req.(*MultipleTickerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataManagementService_ServiceDesc is the grpc.ServiceDesc for DataManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DataManagementService",
	HandlerType: (*DataManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMultipleQuotes",
			Handler:    _DataManagementService_GetMultipleQuotes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data_management.proto",
}
